server:
  name: "analytics-service"
  host: "localhost"
  port: ":65000"

gateway:
  host: "localhost"
  port: ":65001"

logger:
  log_level: "debug"

analytics:
  api_key: ""

tracing:
  jaeger_uri: ""
  event_queue_len: 3000

database:
  uri: "uri"
